import RealityKit
import ARKit
import Vision
import CoreML

final class DetectionService {
    private weak var arView: ARView?
    private let store: SceneStore
    private let queue = DispatchQueue(label: "com.mira.detection", qos: .userInitiated)
    private var isRunning = false
    private let model: VNCoreMLModel
    private let confidenceThreshold: Float = 0.4

    init(arView: ARView, store: SceneStore) {
        self.arView = arView
        self.store = store
        // YOLOv8n is the Swift class auto-generated by Xcode from YOLOv8n.mlpackage
        guard let coreMLModel = try? VNCoreMLModel(for: YOLOv8n(configuration: MLModelConfiguration()).model) else {
            fatalError("YOLOv8n.mlpackage not found — add it to the Mira target in Xcode")
        }
        self.model = coreMLModel
    }

    func start() {
        isRunning = true
        scheduleNext()
    }

    func stop() { isRunning = false }

    private func scheduleNext() {
        queue.asyncAfter(deadline: .now() + 0.5) { [weak self] in self?.runDetection() }
    }

    private func runDetection() {
        guard isRunning else { return }
        defer { scheduleNext() }

        guard let arView = arView,
              let frame = arView.session.currentFrame else { return }

        let request = VNCoreMLRequest(model: model) { [weak self] req, _ in
            guard let self,
                  let results = req.results as? [VNRecognizedObjectObservation] else { return }
            self.processResults(results, frame: frame, arView: arView)
        }
        // Use full frame rather than center crop so edges are covered
        request.imageCropAndScaleOption = .scaleFill

        // Camera sensor is landscape; phone held portrait = .right orientation for Vision
        let handler = VNImageRequestHandler(
            cvPixelBuffer: frame.capturedImage,
            orientation: .right,
            options: [:]
        )
        try? handler.perform([request])
    }

    private func processResults(_ observations: [VNRecognizedObjectObservation],
                                frame: ARFrame, arView: ARView) {
        for obs in observations {
            guard obs.confidence >= confidenceThreshold,
                  let label = obs.labels.first?.identifier else { continue }

            let pos = Raycaster.raycast(in: frame, arView: arView, bbox: obs.boundingBox)
            print("detected: \(label) @ \(pos)")

            Task { @MainActor [weak self] in
                self?.store.upsert(label: label, position: pos, confidence: obs.confidence)
            }
        }
    }
}
